---
id:  <%= p('service.id') %>
name: <%= p('service.name') %>
description: |-
  <%= p('service.description') %>
type: <%= p('service.type') %>
tags:
<% p('service.tags', []).each do |tag| -%>
  - <%= tag %>
<% end -%>
bindable: true
metadata: {}
plan_updateable: true
<% if p('service.limit') > 0 -%>limit: <%= p('service.limit') %><% end -%>

