---
credentials:
<% if p("cf.system_domain") != "" -%>
  dashboard_url: (( concat "https://" name ".<%= p("cf.system_domain") %>/#/login/"  meta.username "/" meta.password ))
  api_url:       (( concat "https://" name ".<%= p("cf.system_domain") %>/api" ))
<% else -%>
<% if p("rabbitmq.tls.enabled") -%>
  dashboard_url: (( concat "https://" credentials.hostnames[0] ":" credentials.tls_mgmt_port "/#/login/"  meta.username "/" meta.password ))
  api_url:       (( concat "https://" credentials.hostnames[0] ":" credentials.tls_mgmt_port "/api" ))
<% else -%>
  dashboard_url: (( concat "http://" credentials.hostnames[0] ":" credentials.mgmt_port "/#/login/"  meta.username "/" meta.password ))
  api_url:       (( concat "http://" credentials.hostnames[0] ":" credentials.mgmt_port "/api" ))
<% end -%>
<% end -%>
  monitoring_username: (( grab meta.username-monitoring ))
  monitoring_password: (( grab meta.password-monitoring ))
  admin_username:      (( grab meta.username ))
  admin_password:      (( grab meta.password ))
  rmq_port:      5672
  tls_port:      5671
  mgmt_port:     15672
  tls_mgmt_port: 15671
  hosts:         (( grab jobs.node.ips ))
  vhost:         (( grab params.instance_id || "/" ))
  username:      (( grab meta.username-app ))
  password:      (( grab meta.password-app ))
<% if ! p("rabbitmq.tls.enabled") -%>
  uris:          (( cartesian-product "amqp://" meta.username-app ":" meta.password-app "@" jobs.node.ips ":" credentials.rmq_port ))
  uri:           (( grab credentials.uris[0] ))
<% else -%>
  uris:          (( cartesian-product "amqps://" meta.username-app ":" meta.password-app "@" jobs.node.ips ":" credentials.tls_port ))
  uri:           (( grab credentials.uris[0] ))
<% end -%>
  hostnames:     (( grab jobs.node.ips ))
  hostname:      (( grab credentials.hosts[0] ))
  protocols:
<% if ! p("rabbitmq.tls.enabled") || (p("rabbitmq.tls.enabled") && p("rabbitmq.tls.dual-mode")) -%>
    amqp:
      username:  (( grab meta.username-app ))
      password:  (( grab meta.password-app ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      vhost:     (( grab params.instance_id || "/" ))
      port: 5672
      ssl: false
      uris:      (( cartesian-product "amqp://" meta.username-app ":" meta.password-app "@" jobs.node.ips ":" credentials.rmq_port ))
      uri:       (( grab credentials.protocols.amqp.uris[0] ))
<% end -%>
<% if p("rabbitmq.tls.enabled") -%>
    amqps:
      username:  (( grab meta.username-app ))
      password:  (( grab meta.password-app ))
      host:      (( grab jobs.node.ips[0] ))
      port: 5671
      vhost:     (( grab params.instance_id || "/" ))
      uris:      (( cartesian-product "amqps://" meta.username-app ":" meta.password-app "@" jobs.node.ips ":" credentials.tls_port ))
      uri:       (( grab credentials.protocols.amqps.uris[0] ))
      ssl: true
<% end -%>
<% if ! p("rabbitmq.tls.enabled") || (p("rabbitmq.tls.enabled") && p("rabbitmq.tls.dual-mode")) -%>
    management:
      username:  (( grab meta.username-app ))
      password:  (( grab meta.password-app ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      path: "/api"
      port: 15672
      ssl: false
      uris:      (( cartesian-product "http://" meta.username-app ":" meta.password-app "@" jobs.node.ips ":" credentials.mgmt_port "/api" ))
      uri:       (( grab credentials.protocols.management.uris[0] ))
<% end -%>
<% if p("rabbitmq.tls.enabled") -%>
    management_tls:
      username:  (( grab meta.username-app ))
      password:  (( grab meta.password-app ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      path: "/api"
      port: 15671
      ssl: true
      uris:      (( cartesian-product "https://" meta.username-app ":" meta.password-app "@" jobs.node.ips ":" credentials.tls_mgmt_port "/api" ))
      uri:       (( grab credentials.protocols.management_tls.uris[0] ))
<% end -%>