#!/bin/bash
set -eu

safe gen $CREDENTIALS/rabbitmq/system username
safe gen $CREDENTIALS/rabbitmq/system password

safe gen $CREDENTIALS/rabbitmq/management username
safe gen $CREDENTIALS/rabbitmq/management password

exit 0
